### ISSUE TITLE
[question] does this support local http client / remote http server?

### ISSUE THREAD

**Issue by atesin** [qub1750ul/Arduino_HTTP#4]
so despite the name (full implementation), it seems to me this library only supports half implementation.. (local server but no local client)

i am looking for both, a local http service listening and responding for remote http client requests, and a local http client sending requests and getting responses from a remote http server

im a little confused, what do you mean with full implementation?, full standard compilant?, full duplex?

does this library supports local http client with remote http server responses processing?

**Comment by qub1750ul** [comment]
As stated in the readme:
> DEVELOPER NOTICE :
>
> Currently this is a functional implementation of HTTP.
> It's my intention to complete it as stated above, but when this will happen is undefined.

This library was born in lack of flexible enough Arduino-compatible HTTP implementations on GitHub, and was developed until suitable for my use case at the time.
Since then the project is on hiatus due to general lack of time.

Here "full" is meant as "full tool suite", so with both the client and server component.
To this date only the server is implemented though.
The client component however was meant mainly as a convenience feature, since there are already many good HTTP/Arduino client-only libraries here on GitHub that should be "plug and play" compatible with this server.
